patient_list = [
    {
        "patient_id": "0001",
        "name": "John Doe",
        "identification_no": "ID-5678",
        "date_of_brth": "1990-01-01",
        "address": "123 Main St",
        "phone_no": "555-1234",
        "email": "jane.doe@example.com",
        "profession": "Teacher",
        "general_information": {
            "blood_group": "AB+",
            "allergies": ["Pollen", "Penicillin"],
            "heart_condition": True,
            "diabetes": False,
            "smoking_history": None,
            "asthema": None,
        },
        "physical_attributes": [
            {"name": "Height", "value": 170.0, "date_added": "2021-09-01"},
            {"name": "Weight", "value": 70.0, "date_added": "2021-09-01"},
        ],
    },
    {
        "patient_id": "0002",
        "name": "Shamit Fatin",
        "identification_no": "ID-9876",
        "date_of_brth": "1985-05-10",
        "address": "456 Elm St",
        "phone_no": "555-5678",
        "email": "john.smith@example.com",
        "profession": "Engineer",
        "general_information": {
            "blood_group": "O+",
            "allergies": None,
            "heart_condition": None,
            "diabetes": True,
            "smoking_history": False,
            "asthema": None,
        },
        "physical_attributes": [
            {"name": "Height", "value": 180.0, "date_added": "2022-01-15"},
            {"name": "Weight", "value": 80.0, "date_added": "2022-01-15"},
        ],
    },
    {
        "patient_id": "0003",
        "name": "Zeeon",
        "identification_no": "ID-2468",
        "date_of_brth": "1978-11-20",
        "address": "789 Oak Ave",
        "phone_no": "555-9012",
        "email": "jane.smith@example.com",
        "profession": "Nurse",
        "general_information": {
            "blood_group": "B-",
            "allergies": ["Shellfish", "Peanuts"],
            "heart_condition": False,
            "diabetes": False,
            "smoking_history": None,
            "asthema": None,
        },
        "physical_attributes": None,
    },
    {
        "patient_id": "0004",
        "name": "Fahmid Azim",
        "identification_no": "ID-2222",
        "date_of_brth": "1995-07-04",
        "address": "111 First St",
        "phone_no": "555-1111",
        "email": "bob.johnson@example.com",
        "profession": "Student",
        "general_information": {
            "blood_group": "A+",
            "allergies": ["Dust", "Cats", "Milk"],
            "heart_condition": None,
            "diabetes": None,
            "smoking_history": None,
            "asthema": True,
        },
        "physical_attributes": [
            {"name": "Height", "value": 165.0, "date_added": "2023-02-10"},
            {"name": "Height", "value": 166.0, "date_added": "2024-02-10"},
            {"name": "Weight", "value": 60.0, "date_added": "2023-02-10"},
        ],
    },
]
